In [ ]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
import numpy as np
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(6).reshape(3,2)
result = np.dot(arr1, arr2)
print(result)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [ ]:
#  How to find common values between two arrays?
import numpy as np
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(6).reshape(3,2)
commons = np.intersect1d(arr1, arr2)
print(commons)

[0 1 2 3 4 5]


In [ ]:
# Create a 5x5 matrix with row values ranging from 0 to 4
import numpy as np
arr = np.zeros((5,5), dtype=int)
arr = arr + np.arange(5)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
import numpy as np
arr = np.linspace(0,1, 12)
print(arr[1:-1])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
# Consider two random arrays A and B, check if they are equal
import numpy as np
A = np.random.randint(0,5, 10, dtype=int)
B = np.random.randint(0,5, 10, dtype=int)
is_equal = np.array_equal(A, B)
print(is_equal)

False


In [ ]:
# Create random vector of size 10 and replace the maximum value by 0
import numpy as np
arr = np.random.rand(10)
arr[arr.argmax()] = 0
print(arr)

0.9977930835818184
[0.18906881 0.7256369  0.30469211 0.09451195 0.11182067 0.55501893
 0.59492718 0.91327491 0.         0.87259508]


In [ ]:
# Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))


In [ ]:
# Print the minimum and maximum representable values for each numpy scalar type
import numpy as np
int8 = np.iinfo(np.int8)
# print(int8.max)
# print(int8.min)

int16 = np.iinfo(np.int16)
# print(int16.max)
# print(int16.min)

int32 = np.iinfo(np.int32)
# print(int32.max)
# print(int32.min)

int64 = np.iinfo(np.int64)
# print(int64.max)
# print(int64.min)

float32 = np.finfo(np.float32)
# print(float32.max)
# print(float32.min)


3.4028235e+38
-3.4028235e+38


In [ ]:
# How to print all the values of an array?
import numpy as np
import sys
arr = np.arange(1001)
np.set_printoptions(threshold=sys.maxsize)
print(arr)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

In [ ]:
# How to find the closest value (to a given scalar) in a vector?
import numpy as np
arr = np.array([1,3,4,5,7,8,8,9,9,34,56,77])
given_number = 40
i = np.abs(arr - given_number)
print(i.min() + given_number)

46


In [ ]:
# How to convert a float (32 bits) array into an integer (32 bits) array in place?
arr = np.array([1.1, 2.5, 3.9, 4.2], dtype=np.float32)
arr[:] = arr.astype(np.int32)
print(arr)

[1. 2. 3. 4.]


In [ ]:
# Subtract the mean of each row of a matrix
import numpy as np
arr = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
row_means = arr.mean(axis=1, keepdims=True)
result = arr - row_means
print(result)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [5]:

# How to sort an array by the nth column?
import numpy as np
arr = np.array([
    [10,  3,  7],
    [ 2,  9,  1],
    [ 5,  4,  8],
])

index = np.argsort(arr[:, 0])
sorted_arr = arr[index]
print(sorted_arr)

[[ 2  9  1]
 [ 5  4  8]
 [10  3  7]]


In [8]:
# How to tell if a given 2D array has null columns?
import numpy as np
arr = np.array([
    [0, 2, 0],
    [0, 5, 0],
    [0, 7, 0]
])

is_null = np.all(arr == 0, axis=0)
print(is_null)

[False False False]


In [12]:
#  How to get the diagonal of a dot product?
arr1 = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3],
])
arr2 = np.array([
    [5,6,7],
    [5,6,7],
    [5,6,7],
])

dot_product = arr1 @ arr2

print(np.diag(dot_product))

[30 36 42]


In [13]:
# Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)?
import numpy as np

A = np.random.rand(5, 5, 3)
B = np.random.rand(5, 5)

result = A * B[:, :, None]
print(result.shape)

(5, 5, 3)


In [14]:
# How to swap two rows of an array?
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr[[0,1]] = arr[[1,0]]
print(arr)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [16]:
import numpy as np

Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

R = np.array([Z[i:i+4] for i in range(len(Z) - 3)])

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [17]:
#  How to find the most frequent value in an array?
import numpy as np

A = np.array([
    [[1,2,2],
     [3,3,3]],

    [[4,1,2],
     [3,3,5]]
])

values, counts = np.unique(A, return_counts=True)
mode = values[counts.argmax()]

print(mode)

3
