In [7]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
import numpy as np
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(6).reshape(3,2)
result = np.dot(arr1, arr2)
print(result)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [8]:
#  How to find common values between two arrays?
import numpy as np
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(6).reshape(3,2)
commons = np.intersect1d(arr1, arr2)
print(commons)

[0 1 2 3 4 5]


In [19]:
# Create a 5x5 matrix with row values ranging from 0 to 4
import numpy as np
arr = np.zeros((5,5), dtype=int)
arr = arr + np.arange(5)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [22]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
import numpy as np
arr = np.linspace(0,1, 12)
print(arr[1:-1])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [25]:
# Consider two random arrays A and B, check if they are equal
import numpy as np
A = np.random.randint(0,5, 10, dtype=int)
B = np.random.randint(0,5, 10, dtype=int)
is_equal = np.array_equal(A, B)
print(is_equal)

False
