In [7]:
import numpy as np
arr = np.zeros(10)
# print(arr)
# print(arr.itemsize * arr.size)
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [8]:
import numpy as np
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
import numpy as np
arr = np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [10]:
import numpy as np
arr = np.arange(10,49)
print(arr[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
import numpy as np
arr = np.arange(0,9)
print(arr.reshape((3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
print(arr[arr != 0])
print(arr.nonzero())

[1 2 4]
(array([0, 1, 4]),)


In [16]:
import numpy as np
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
import numpy as np
arr = np.random.rand(3,3,3)
print(arr)

[[[0.74889613 0.35927796 0.48703582]
  [0.3200628  0.19668258 0.74936181]
  [0.21588702 0.37834924 0.44532342]]

 [[0.47602417 0.09419513 0.79563243]
  [0.37495819 0.94825936 0.8313276 ]
  [0.08626623 0.62881656 0.97193202]]

 [[0.0416755  0.18054506 0.71545427]
  [0.04526638 0.21264002 0.77172735]
  [0.25060356 0.33567179 0.09471684]]]


In [18]:
import numpy as np
arr = np.random.random(30)
print(arr.mean())

0.5747967056300013
