In [1]:
import numpy as np
data = np.array([
    [1,3,4],
    [1,3,4],
    [1,3,4],
])
data

array([[1, 3, 4],
       [1, 3, 4],
       [1, 3, 4]])

In [2]:
import numpy as np
data = np.random.rand(3,3)
data

array([[0.03015391, 0.15805032, 0.83485996],
       [0.66584583, 0.57135455, 0.56534747],
       [0.49099327, 0.55510824, 0.11772254]])

In [3]:
import numpy as np
data = np.random.rand(10,10)
print(data.min())
print(data.max())

0.00844572262845178
0.9804131596802126


In [7]:
import numpy as np
given_array = np.array([1,2,3,4,5,6,7,8,9])
given_array[(given_array > 3) & (given_array < 8)] = given_array[(given_array > 3) & (given_array < 8)] * -1
print(given_array)

[ 1  2  3 -4 -5 -6 -7  8  9]


In [16]:
import numpy as np
data = np.random.random(10)
print(data)
data.sort()
print(data)

[0.66311462 0.12766383 0.80075683 0.25633738 0.37148937 0.90895506
 0.57695341 0.84019569 0.24285329 0.23474805]
[0.12766383 0.23474805 0.24285329 0.25633738 0.37148937 0.57695341
 0.66311462 0.80075683 0.84019569 0.90895506]
