In [ ]:
import numpy as np
arr = np.zeros(10)
# print(arr)
# print(arr.itemsize * arr.size)
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [ ]:
import numpy as np
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
arr = np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
import numpy as np
arr = np.arange(10,49)
print(arr[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
import numpy as np
arr = np.arange(0,9)
print(arr.reshape((3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
print(arr[arr != 0])
print(arr.nonzero())

[1 2 4]
(array([0, 1, 4]),)


In [ ]:
import numpy as np
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
arr = np.random.rand(3,3,3)
print(arr)

[[[0.74889613 0.35927796 0.48703582]
  [0.3200628  0.19668258 0.74936181]
  [0.21588702 0.37834924 0.44532342]]

 [[0.47602417 0.09419513 0.79563243]
  [0.37495819 0.94825936 0.8313276 ]
  [0.08626623 0.62881656 0.97193202]]

 [[0.0416755  0.18054506 0.71545427]
  [0.04526638 0.21264002 0.77172735]
  [0.25060356 0.33567179 0.09471684]]]


In [ ]:
import numpy as np
arr = np.random.random(30)
print(arr.mean())

0.5747967056300013


In [ ]:
import numpy as np
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
import numpy as np
arr = np.ones((5,5))
arr = np.pad(arr, pad_width=2, mode='constant', constant_values=0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
import numpy as np
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [18]:
import numpy as np
arr = np.diag(np.arange(1,5), k=-1)
print(arr)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [24]:
import numpy as np
arr = np.ones((8,8))
arr[::2, 1::2] = 0
arr[1::2, ::2] = 0
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [33]:
import numpy as np
arr = np.random.rand(6,7,8)
index = np.unravel_index(99, arr.shape)
print(index)

(np.int64(1), np.int64(5), np.int64(3))


In [47]:
import numpy as np
arr = np.tile(([0,1], [1,0]), (4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [55]:
import numpy as np
arr1 = np.arange(15)
arr1 = np.reshape(arr1, (5,3))
arr2 = np.arange(6)
arr2 = np.reshape(arr2, (3,2))
result = arr1 @ arr2
print(result)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [57]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)

[ 1  2  3 -4 -5 -6 -7  8  9]


In [58]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [59]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,5,6,7,8])
print(np.intersect1d(arr1, arr2))

[4 5]


In [64]:
import numpy as np
print(np.datetime64("today"))
print(np.datetime64("today") - np.timedelta64(2))
print(np.datetime64("today") + np.timedelta64(1))

2026-03-02
2026-02-28
2026-03-03


In [71]:
import numpy as np
arr = np.arange( '2016-06', '2016-07', dtype='datetime64[D]',)
print(arr)

['2016-06-01' '2016-06-02' '2016-06-03' '2016-06-04' '2016-06-05'
 '2016-06-06' '2016-06-07' '2016-06-08' '2016-06-09' '2016-06-10'
 '2016-06-11' '2016-06-12' '2016-06-13' '2016-06-14' '2016-06-15'
 '2016-06-16' '2016-06-17' '2016-06-18' '2016-06-19' '2016-06-20'
 '2016-06-21' '2016-06-22' '2016-06-23' '2016-06-24' '2016-06-25'
 '2016-06-26' '2016-06-27' '2016-06-28' '2016-06-29' '2016-06-30']


In [80]:
import numpy as np
arr = np.array([1.2, 23.3, 46.5])
# print(arr - arr % 1)
# print(np.floor(arr))
# arr = arr.astype(int)
print(np.trunc(arr))

[ 1. 23. 46.]


In [89]:
import numpy as np
arr = np.ones((5,5))
arr += np.arange(0,5)
# np.pad(arr)
print(arr)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]
